### ISSUE TITLE
stampit instance passed in as state to another stampit loses its stampiness

### ISSUE THREAD

**Issue by jomido** [ericelliott/stampit#54] opened 2015-03-24 19:50 UTC
I've got a live demo here: http://codepen.io/anon/pen/qEgjyo (open the console to see the result).

The code to reproduce is at the link above, but I'll repeat it here:

    var a = stampit().state({
      n: 1
    }).methods({
      num:function () { return this.n; }
    })();

    console.log(a); // b {n: 1, num: function}

    var b = stampit().state({a: a})();

    console.log(b.a); // Object {n: 1}

If I pass a stampit instance in as state to a stampit factory, the factory un-stampifies the instance into a plain Object. (Do forgive me if my terms are inaccurate.) As a consequence, the 'num' method is missing from b's reference to a.

Is this intended behaviour? If not, please consider this a bug. If this is intended behaviour, what is the reason for it, and/or is there a different pattern I should be aware of?

**Comment by koresar** [comment] 2015-03-24 23:33
That is by design. The state does not copy any `.prototype` properties from the given variable `a`. Moreover, it performs cloning of the variable `a`, i.e. not referencing.

**Comment by jomido** [comment] 2015-03-24 23:46
OK, thanks. The stampit API docs do mention that:

@param {Object} [state] A map of property names and values to clone for each new object.

I apologize for missing this. To compose by reference, then, the options are either

a) enclose(), or
b) assignment after instance creation

**Comment by koresar** [comment] 2015-03-24 23:47
@ericelliott Here is the third person who needs composing by reference.

We have to add it to v2.0 I reckon.

**Comment by ericelliott** [comment] 2015-03-25 04:50
Why? Stampit is already perfectly capable of producoling the desired stamp with `.enclose()`.

**Comment by jomido** [comment] 2015-03-25 13:20
It seems to me that enclose() can be used conceptually the same as a constructor or init method. Instead of passing in the initial data as arguments, one grants the function passed to enclose access to the initial data via scope (or closure).  Like so:

    var refInstance = stampit().state(...).methods(...)();
    var init = function () {
        this.ref = refInstance
    };
  
    var myInstance = stampit().state(...).methods(...).enclose(init)();

This not only works but feels good, too. :)

**Comment by koresar** [comment] 2015-05-19 22:51
We might inbuild this feature into v2.x as it is very popular request. See #55 

Closing this one as @jomido has found the proper solution. Well done, mate!

**Closed by koresar** 2015-05-19 22:51 UTC
